name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Prepare python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup Rust Toolchain for GitHub CI
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Compile executable
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: python
          path: target/debug/python
      # - name: Compile and release
      #   uses: rust-build/rust-build.action@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     RUSTTARGET: ${{ matrix.target }}
      #     ARCHIVE_TYPES: ${{ matrix.archive }}
